Repository prgrms-web-devcourse-final-project/WEB1_1_Postman_BE, pull requests merged in 2024-12, with the labels that each got.

#30 Feature/#25 : `신고` 기능 구현
  src/main/java/postman/bottler/complaint/controller/ComplaintController.java
  src/main/java/postman/bottler/complaint/domain/Complaint.java
  src/main/java/postman/bottler/complaint/domain/Complaints.java
  src/main/java/postman/bottler/complaint/domain/KeywordComplaint.java
  src/main/java/postman/bottler/complaint/domain/KeywordReplyComplaint.java
  src/main/java/postman/bottler/complaint/domain/MapComplaint.java
  src/main/java/postman/bottler/complaint/domain/MapReplyComplaint.java
  src/main/java/postman/bottler/complaint/domain/complaint.java
  src/main/java/postman/bottler/complaint/dto/ComplaintDTO.java
  src/main/java/postman/bottler/complaint/dto/request/ComplaintRequestDTO.java
  src/main/java/postman/bottler/complaint/dto/response/ComplaintResponseDTO.java
  src/main/java/postman/bottler/complaint/exception/ComplaintExceptionHandler.java
  src/main/java/postman/bottler/complaint/exception/DuplicateComplainException.java
  src/main/java/postman/bottler/complaint/exception/InvalidComplainException.java
  src/main/java/postman/bottler/complaint/infra/keyword/JpaKeywordComplaintRepository.java
  src/main/java/postman/bottler/complaint/infra/keyword/JpaKeywordReplyComplaintRepository.java
  src/main/java/postman/bottler/complaint/infra/keyword/KeywordComplaintEntity.java
  src/main/java/postman/bottler/complaint/infra/keyword/KeywordComplaintRepositoryImpl.java
  src/main/java/postman/bottler/complaint/infra/keyword/KeywordReplyComplaintEntity.java
  src/main/java/postman/bottler/complaint/infra/keyword/KeywordReplyComplaintRepositoryImpl.java
  src/main/java/postman/bottler/complaint/infra/map/JpaMapComplaintRepository.java
  src/main/java/postman/bottler/complaint/infra/map/JpaMapReplyComplaintRepository.java
  src/main/java/postman/bottler/complaint/infra/map/MapComplaintEntity.java
  src/main/java/postman/bottler/complaint/infra/map/MapComplaintRepositoryImpl.java
  src/main/java/postman/bottler/complaint/infra/map/MapReplyComplaintEntity.java
  src/main/java/postman/bottler/complaint/infra/map/MapReplyComplaintRepositoryImpl.java
  src/main/java/postman/bottler/complaint/service/ComplaintService.java
  src/main/java/postman/bottler/complaint/service/ComplaintServiceImpl.java
  src/main/java/postman/bottler/complaint/service/KeywordComplaintRepository.java
  src/main/java/postman/bottler/complaint/service/KeywordReplyComplaintRepository.java
  src/main/java/postman/bottler/complaint/service/MapComplaintRepository.java
  src/main/java/postman/bottler/complaint/service/MapReplyComplaintRepository.java
  src/main/java/postman/bottler/global/response/code/ErrorStatus.java
  src/test/java/postman/bottler/complaint/domain/ComplaintsTest.java
  src/test/java/postman/bottler/complaint/infra/KeywordComplaintRepositoryTest.java
  src/test/java/postman/bottler/complaint/infra/MapComplaintRepositoryTest.java
  src/test/java/postman/bottler/complaint/service/ComplaintServiceTest.java
Labels: feature

#49 [Refactor/#48] 알림 테이블 redis로 변경
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  build.gradle
  src/main/java/postman/bottler/config/FcmConfig.java
  src/main/java/postman/bottler/config/RedisConfig.java
  src/main/java/postman/bottler/notification/domain/LetterNotification.java
  src/main/java/postman/bottler/notification/domain/Notification.java
  src/main/java/postman/bottler/notification/domain/Notifications.java
  src/main/java/postman/bottler/notification/dto/response/NotificationResponseDTO.java
  src/main/java/postman/bottler/notification/infra/JpaNotificationRepository.java
  src/main/java/postman/bottler/notification/infra/NotificationEntity.java
  src/main/java/postman/bottler/notification/infra/NotificationRepositoryImpl.java
  src/main/java/postman/bottler/notification/infra/RedisNotification.java
  src/main/java/postman/bottler/notification/infra/RedisNotificationRepositoryImpl.java
  src/main/java/postman/bottler/notification/service/NotificationRepository.java
  src/main/java/postman/bottler/notification/service/NotificationService.java
  src/main/resources/application.yml
  src/test/java/postman/bottler/label/service/LabelServiceTest.java
  src/test/java/postman/bottler/mapletter/domain/MapLetterTest.java
  src/test/java/postman/bottler/mapletter/service/MapLetterServiceTest.java
  src/test/java/postman/bottler/mapletter/service/PaperServiceTest.java
  src/test/java/postman/bottler/notification/service/NotificationServiceTest.java
  src/test/resources/application.yml
Labels: refactor

#54 Feature/#53 스케쥴러 config 등록 및 구현해야 할 기능 작성
  src/main/java/postman/bottler/BottlerApplication.java
  src/main/java/postman/bottler/scheduler/SchedulerConfig.java
Labels: feature

#65 Feature/#64 ci cd
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  docker-compose/docker-compose.yml
Labels: feature, CI-CD

#63 [Feature/#55] : 유저 정지 인프라 계층 구현
  src/main/java/postman/bottler/user/domain/Ban.java
  src/main/java/postman/bottler/user/infra/BanRepositoryImpl.java
  src/main/java/postman/bottler/user/infra/JpaBanRepository.java
  src/main/java/postman/bottler/user/infra/entity/BanEntity.java
  src/main/java/postman/bottler/user/service/BanRepository.java
  src/main/java/postman/bottler/user/service/BanService.java
Labels: feature

#67 [Hotfix/#66] createdAt 관리 계층 수정
  src/main/java/postman/bottler/complaint/controller/ComplaintController.java
  src/main/java/postman/bottler/complaint/domain/Complaint.java
  src/main/java/postman/bottler/complaint/domain/KeywordComplaint.java
  src/main/java/postman/bottler/complaint/domain/KeywordReplyComplaint.java
  src/main/java/postman/bottler/complaint/domain/MapComplaint.java
  src/main/java/postman/bottler/complaint/domain/MapReplyComplaint.java
  src/main/java/postman/bottler/complaint/infra/keyword/KeywordComplaintEntity.java
  src/main/java/postman/bottler/complaint/infra/keyword/KeywordReplyComplaintEntity.java
  src/main/java/postman/bottler/complaint/infra/map/MapComplaintEntity.java
  src/main/java/postman/bottler/complaint/infra/map/MapReplyComplaintEntity.java
  src/test/java/postman/bottler/complaint/service/ComplaintServiceTest.java
Labels: fix

#74 fix: #72 지도 편지 userDetails 붙이기
  src/main/java/postman/bottler/config/SecurityConfig.java
  src/main/java/postman/bottler/mapletter/controller/MapLetterController.java
Labels: fix

#75 fix: #72 라벨 userDetails
  src/main/java/postman/bottler/label/controller/LabelController.java
  src/main/java/postman/bottler/label/domain/Label.java
  src/main/java/postman/bottler/label/dto/LabelResponseDTO.java
  src/main/java/postman/bottler/label/dto/request/LabelRequestDTO.java
  src/main/java/postman/bottler/label/service/LabelService.java
  src/main/java/postman/bottler/user/infra/UserRepositoryImpl.java
  src/main/java/postman/bottler/user/service/UserRepository.java
  src/main/java/postman/bottler/user/service/UserService.java
  src/test/java/postman/bottler/label/domain/LabelTest.java
  src/test/java/postman/bottler/label/service/LabelServiceTest.java
Labels: fix

#73 [fix#72]: `신고`, `알림` 도메인 CustomUserDetails 적용으로 인한 수정
  src/main/java/postman/bottler/complaint/controller/ComplaintController.java
  src/main/java/postman/bottler/complaint/dto/request/ComplaintRequestDTO.java
  src/main/java/postman/bottler/notification/controller/NotificationController.java
  src/main/java/postman/bottler/notification/dto/request/SubscriptionRequestDTO.java
  src/main/java/postman/bottler/notification/dto/request/UserNotificationRequestDTO.java
Labels: fix

#77 fix: 키워드 편지 userDetails 적용
  src/main/java/postman/bottler/letter/controller/LetterBoxController.java
  src/main/java/postman/bottler/letter/controller/LetterController.java
  src/main/java/postman/bottler/letter/controller/ReplyLetterController.java
  src/main/java/postman/bottler/letter/service/DeleteManagerService.java
  src/main/java/postman/bottler/letter/service/LetterBoxService.java
  src/main/java/postman/bottler/letter/service/LetterService.java
  src/main/java/postman/bottler/letter/service/ReplyLetterService.java
Labels: fix

#80 hotfix: swagger gradle 버전 충돌 해결
  build.gradle
Labels: CI-CD

#83 feat: cors 설정 추가
  src/main/java/postman/bottler/config/SecurityConfig.java
Labels: feature

#84 Feature: cors 설정 추가
  src/main/java/postman/bottler/config/SecurityConfig.java
Labels: feature

#86 Feature/#52 soft delete
  src/main/java/postman/bottler/letter/domain/LetterBox.java
  src/main/java/postman/bottler/letter/infra/LetterBoxRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/LetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/LetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/entity/LetterBoxEntity.java
  src/main/java/postman/bottler/letter/service/LetterRepository.java
  src/main/java/postman/bottler/letter/service/LetterService.java
  src/main/java/postman/bottler/letter/service/ReplyLetterRepository.java
  src/main/java/postman/bottler/letter/service/ReplyLetterService.java
Labels: feature

#90 Feature/#19 유저 기능 추가
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/main/java/postman/bottler/config/SecurityConfig.java
  src/main/java/postman/bottler/global/response/code/ErrorStatus.java
  src/main/java/postman/bottler/user/controller/OAuthController.java
  src/main/java/postman/bottler/user/controller/UserController.java
  src/main/java/postman/bottler/user/domain/EmailCode.java
  src/main/java/postman/bottler/user/domain/EmailForm.java
  src/main/java/postman/bottler/user/domain/Provider.java
  src/main/java/postman/bottler/user/domain/User.java
  src/main/java/postman/bottler/user/dto/request/AuthEmailRequestDTO.java
  src/main/java/postman/bottler/user/dto/request/ChangePasswordRequestDTO.java
  src/main/java/postman/bottler/user/dto/request/CheckDuplicateNicknameRequestDTO.java
  src/main/java/postman/bottler/user/dto/request/CheckPasswordRequestDTO.java
  src/main/java/postman/bottler/user/dto/request/NicknameRequestDTO.java
  src/main/java/postman/bottler/user/dto/request/SignInRequestDTO.java
  src/main/java/postman/bottler/user/dto/request/SignUpRequestDTO.java
  src/main/java/postman/bottler/user/dto/request/UserRequestDTO.java
  src/main/java/postman/bottler/user/dto/response/UserResponseDTO.java
  src/main/java/postman/bottler/user/exception/EmailCodeException.java
  src/main/java/postman/bottler/user/exception/KakaoAuthCodeException.java
  src/main/java/postman/bottler/user/exception/KakaoException.java
  src/main/java/postman/bottler/user/exception/UserExceptionHandler.java
  src/main/java/postman/bottler/user/infra/EmailCodeJpaRepository.java
  src/main/java/postman/bottler/user/infra/EmailCodeRepositoryImpl.java
  src/main/java/postman/bottler/user/infra/ProfileImageJpaRepository.java
  src/main/java/postman/bottler/user/infra/ProfileImageRepositoryImpl.java
  src/main/java/postman/bottler/user/infra/UserJpaRepository.java
  src/main/java/postman/bottler/user/infra/UserRepositoryImpl.java
  src/main/java/postman/bottler/user/infra/entity/BanEntity.java
  src/main/java/postman/bottler/user/infra/entity/EmailCode.java
  src/main/java/postman/bottler/user/infra/entity/EmailCodeEntity.java
  src/main/java/postman/bottler/user/infra/entity/ProfileImageEntity.java
  src/main/java/postman/bottler/user/infra/entity/RefreshTokenEntity.java
  src/main/java/postman/bottler/user/infra/entity/UserEntity.java
  src/main/java/postman/bottler/user/service/BanService.java
  src/main/java/postman/bottler/user/service/EmailCodeRepository.java
  src/main/java/postman/bottler/user/service/EmailService.java
  src/main/java/postman/bottler/user/service/KakaoService.java
  src/main/java/postman/bottler/user/service/ProfileImageRepository.java
  src/main/java/postman/bottler/user/service/UserRepository.java
  src/main/java/postman/bottler/user/service/UserService.java
  src/main/resources/application.yml
Labels: feature

#89 Feature/#81 답장 편지 최근 3개 보여주기
  src/main/java/postman/bottler/letter/service/ReplyLetterService.java
  src/main/java/postman/bottler/mapletter/dto/ReplyProjectDTO.java
  src/main/java/postman/bottler/mapletter/infra/ReplyMapLetterJpaRepository.java
  src/main/java/postman/bottler/mapletter/infra/ReplyMapLetterRepositoryImpl.java
  src/main/java/postman/bottler/mapletter/service/MapLetterService.java
  src/main/java/postman/bottler/mapletter/service/ReplyMapLetterRepository.java
  src/main/java/postman/bottler/reply/controller/ReplyController.java
  src/main/java/postman/bottler/reply/dto/ReplyType.java
  src/main/java/postman/bottler/reply/dto/response/ReplyResponseDTO.java
  src/main/java/postman/bottler/reply/service/ReplyService.java
Labels: feature

#88 [Refactor/#68] 알림 답장 키워드/지도 구분
  src/main/java/postman/bottler/complaint/service/ComplaintService.java
  src/main/java/postman/bottler/notification/controller/NotificationController.java
  src/main/java/postman/bottler/notification/domain/Notification.java
  src/main/java/postman/bottler/notification/domain/NotificationType.java
  src/main/java/postman/bottler/notification/domain/Notifications.java
  src/main/java/postman/bottler/notification/infra/NotificationHashKey.java
  src/main/java/postman/bottler/notification/infra/RedisNotification.java
  src/main/java/postman/bottler/notification/infra/RedisNotificationRepositoryImpl.java
  src/main/java/postman/bottler/notification/service/NotificationService.java
  src/test/java/postman/bottler/notification/domain/LetterNotificationTest.java
  src/test/java/postman/bottler/notification/domain/NotificationTest.java
  src/test/java/postman/bottler/notification/domain/NotificationTypeTest.java
  src/test/java/postman/bottler/notification/service/NotificationServiceTest.java
Labels: refactor

#99 Feature/#85 keyword
  src/main/java/postman/bottler/config/RedisConfig.java
  src/main/java/postman/bottler/keyword/controller/KeywordController.java
  src/main/java/postman/bottler/keyword/domain/Keyword.java
  src/main/java/postman/bottler/keyword/domain/LetterKeyword.java
  src/main/java/postman/bottler/keyword/domain/UserKeyword.java
  src/main/java/postman/bottler/keyword/dto/request/UserKeywordRequestDTO.java
  src/main/java/postman/bottler/keyword/dto/response/KeywordResponseDTO.java
  src/main/java/postman/bottler/keyword/dto/response/UserKeywordResponseDTO.java
  src/main/java/postman/bottler/keyword/infra/KeywordJpaRepository.java
  src/main/java/postman/bottler/keyword/infra/KeywordRepositoryImpl.java
  src/main/java/postman/bottler/keyword/infra/LetterKeywordJdbcRepository.java
  src/main/java/postman/bottler/keyword/infra/LetterKeywordQueryDslRepository.java
  src/main/java/postman/bottler/keyword/infra/LetterKeywordRepositoryImpl.java
  src/main/java/postman/bottler/keyword/infra/UserKeywordJdbcRepository.java
  src/main/java/postman/bottler/keyword/infra/UserKeywordJpaRepository.java
  src/main/java/postman/bottler/keyword/infra/UserKeywordRepositoryImpl.java
  src/main/java/postman/bottler/keyword/infra/entity/KeywordEntity.java
  src/main/java/postman/bottler/keyword/infra/entity/LetterKeywordEntity.java
  src/main/java/postman/bottler/keyword/infra/entity/UserKeywordEntity.java
  src/main/java/postman/bottler/keyword/service/AsyncRecommendationService.java
  src/main/java/postman/bottler/keyword/service/KeywordRepository.java
  src/main/java/postman/bottler/keyword/service/KeywordService.java
  src/main/java/postman/bottler/keyword/service/LetterKeywordRepository.java
  src/main/java/postman/bottler/keyword/service/LetterKeywordService.java
  src/main/java/postman/bottler/keyword/service/RecommendService.java
  src/main/java/postman/bottler/keyword/service/UserKeywordRepository.java
  src/main/java/postman/bottler/keyword/service/UserKeywordService.java
  src/main/java/postman/bottler/letter/controller/LetterController.java
  src/main/java/postman/bottler/letter/domain/Letter.java
  src/main/java/postman/bottler/letter/dto/request/LetterRequestDTO.java
  src/main/java/postman/bottler/letter/dto/response/LetterDetailResponseDTO.java
  src/main/java/postman/bottler/letter/dto/response/LetterResponseDTO.java
  src/main/java/postman/bottler/letter/infra/LetterBoxRepositoryImpl.java
  src/main/java/postman/bottler/letter/service/DeleteManagerService.java
  src/main/java/postman/bottler/letter/service/LetterBoxRepository.java
  src/main/java/postman/bottler/letter/service/LetterBoxService.java
  src/main/java/postman/bottler/letter/service/LetterService.java
  src/main/java/postman/bottler/letter/service/ReplyLetterService.java
  src/main/java/postman/bottler/scheduler/RecommendationScheduler.java
  src/main/java/postman/bottler/scheduler/SchedulerConfig.java
  src/main/resources/application.yml
Labels: feature

#95 Feature/#91 유저 추가 기능
  src/main/java/postman/bottler/global/response/code/ErrorStatus.java
  src/main/java/postman/bottler/user/domain/ProfileImage.java
  src/main/java/postman/bottler/user/domain/Provider.java
  src/main/java/postman/bottler/user/domain/User.java
  src/main/java/postman/bottler/user/exception/UserBanException.java
  src/main/java/postman/bottler/user/exception/UserExceptionHandler.java
  src/main/java/postman/bottler/user/infra/RefreshTokenJpaRepository.java
  src/main/java/postman/bottler/user/infra/RefreshTokenRepositoryImpl.java
  src/main/java/postman/bottler/user/infra/UserRepositoryImpl.java
  src/main/java/postman/bottler/user/infra/entity/UserEntity.java
  src/main/java/postman/bottler/user/service/BanService.java
  src/main/java/postman/bottler/user/service/RefreshTokenRepository.java
  src/main/java/postman/bottler/user/service/UserRepository.java
  src/main/java/postman/bottler/user/service/UserService.java
Labels: feature

#96 Feature/#94 guest map letter find
  src/main/java/postman/bottler/config/SecurityConfig.java
  src/main/java/postman/bottler/mapletter/controller/MapLetterController.java
  src/main/java/postman/bottler/mapletter/domain/MapLetter.java
  src/main/java/postman/bottler/mapletter/infra/MapLetterJpaRepository.java
  src/main/java/postman/bottler/mapletter/infra/MapLetterRepositoryImpl.java
  src/main/java/postman/bottler/mapletter/service/MapLetterRepository.java
  src/main/java/postman/bottler/mapletter/service/MapLetterService.java
Labels: feature

#93 [Feature/#92] `추천 편지 전송`/`유저 정지 해제` Batch 처리
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  build.gradle
  src/main/java/postman/bottler/batch/KeywordBatch.java
  src/main/java/postman/bottler/batch/NotificationWriter.java
  src/main/java/postman/bottler/batch/UnbanBatch.java
  src/main/java/postman/bottler/config/SecurityConfig.java
  src/main/java/postman/bottler/notification/infra/SubscriptionRepositoryImpl.java
  src/main/java/postman/bottler/notification/service/SubscriptionRepository.java
  src/main/java/postman/bottler/scheduler/SchedulerConfig.java
  src/main/java/postman/bottler/user/domain/User.java
  src/main/java/postman/bottler/user/infra/JpaBanRepository.java
  src/main/java/postman/bottler/user/infra/UserJpaRepository.java
  src/main/java/postman/bottler/user/infra/UserRepositoryImpl.java
  src/main/java/postman/bottler/user/infra/entity/BanEntity.java
  src/main/java/postman/bottler/user/service/UserRepository.java
  src/main/resources/application.yml
Labels: feature

#105 fix: #104 타겟 편지 작성시 타겟 유저 닉네임으로 받도록 수정
  src/main/java/postman/bottler/mapletter/domain/MapLetter.java
  src/main/java/postman/bottler/mapletter/dto/request/CreateTargetMapLetterRequestDTO.java
  src/main/java/postman/bottler/mapletter/service/MapLetterService.java
Labels: fix

#107 feature: 키워드 편지 블락 기능 추가
  src/main/java/postman/bottler/config/SecurityConfig.java
  src/main/java/postman/bottler/global/response/code/ErrorStatus.java
  src/main/java/postman/bottler/letter/exception/InvalidLetterTypeException.java
  src/main/java/postman/bottler/letter/exception/LetterExceptionHandler.java
  src/main/java/postman/bottler/letter/infra/LetterBoxJpaRepository.java
  src/main/java/postman/bottler/letter/infra/LetterBoxQueryRepository.java
  src/main/java/postman/bottler/letter/infra/LetterBoxRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/LetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/LetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/service/BlockService.java
  src/main/java/postman/bottler/letter/service/LetterRepository.java
  src/main/java/postman/bottler/letter/service/LetterService.java
  src/main/java/postman/bottler/letter/service/ReplyLetterRepository.java
  src/main/java/postman/bottler/letter/service/ReplyLetterService.java
Labels: feature

#108 Feature/#98 슬랙봇 기능 추가
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  build.gradle
  src/main/java/postman/bottler/mapletter/service/MapLetterService.java
  src/main/java/postman/bottler/slack/SlackConstant.java
  src/main/java/postman/bottler/slack/SlackService.java
  src/main/java/postman/bottler/user/service/UserService.java
  src/main/resources/application.yml
Labels: feature

#109 [Fix/#101] 타 도메인 요청 기능 추가
  src/main/java/postman/bottler/complaint/controller/ComplaintController.java
  src/main/java/postman/bottler/complaint/domain/Complaint.java
  src/main/java/postman/bottler/complaint/domain/ComplaintType.java
  src/main/java/postman/bottler/complaint/domain/Complaints.java
  src/main/java/postman/bottler/complaint/domain/KeywordComplaint.java
  src/main/java/postman/bottler/complaint/domain/KeywordReplyComplaint.java
  src/main/java/postman/bottler/complaint/domain/MapComplaint.java
  src/main/java/postman/bottler/complaint/domain/MapReplyComplaint.java
  src/main/java/postman/bottler/complaint/infra/keyword/KeywordComplaintEntity.java
  src/main/java/postman/bottler/complaint/infra/keyword/KeywordComplaintRepositoryImpl.java
  src/main/java/postman/bottler/complaint/infra/keyword/KeywordReplyComplaintEntity.java
  src/main/java/postman/bottler/complaint/infra/keyword/KeywordReplyComplaintRepositoryImpl.java
  src/main/java/postman/bottler/complaint/infra/map/MapComplaintEntity.java
  src/main/java/postman/bottler/complaint/infra/map/MapComplaintRepositoryImpl.java
  src/main/java/postman/bottler/complaint/infra/map/MapReplyComplaintEntity.java
  src/main/java/postman/bottler/complaint/infra/map/MapReplyComplaintRepositoryImpl.java
  src/main/java/postman/bottler/complaint/service/ComplaintRepository.java
  src/main/java/postman/bottler/complaint/service/ComplaintService.java
  src/main/java/postman/bottler/complaint/service/KeywordComplaintRepository.java
  src/main/java/postman/bottler/complaint/service/KeywordReplyComplaintRepository.java
  src/main/java/postman/bottler/complaint/service/MapComplaintRepository.java
  src/main/java/postman/bottler/complaint/service/MapReplyComplaintRepository.java
Labels: fix

#112 CI-CD/ 배포
  .github/workflows/cd.yml
Labels: CI-CD

#114 Hotfix/#113 security config
  src/main/java/postman/bottler/config/SecurityConfig.java
Labels: hotfix

#127 refactor: security config 설정 추가
  src/main/java/postman/bottler/config/SecurityConfig.java
  src/main/java/postman/bottler/user/auth/JwtFilter.java
Labels: refactor

#120 Feature/#116 letter reply
  src/main/java/postman/bottler/global/response/code/ErrorStatus.java
  src/main/java/postman/bottler/keyword/controller/RecommendationController.java
  src/main/java/postman/bottler/keyword/service/AsyncRecommendationService.java
  src/main/java/postman/bottler/keyword/service/RedisLetterService.java
  src/main/java/postman/bottler/keyword/util/RedisLetterKeyUtil.java
  src/main/java/postman/bottler/letter/controller/LetterController.java
  src/main/java/postman/bottler/letter/domain/Letter.java
  src/main/java/postman/bottler/letter/domain/ReplyLetter.java
  src/main/java/postman/bottler/letter/dto/request/LetterRequestDTO.java
  src/main/java/postman/bottler/letter/dto/request/ReplyLetterRequestDTO.java
  src/main/java/postman/bottler/letter/dto/response/LetterDetailResponseDTO.java
  src/main/java/postman/bottler/letter/dto/response/LetterRecommendHeadersResponseDTO.java
  src/main/java/postman/bottler/letter/dto/response/LetterResponseDTO.java
  src/main/java/postman/bottler/letter/dto/response/ReplyLetterResponseDTO.java
  src/main/java/postman/bottler/letter/exception/DuplicateReplyLetterException.java
  src/main/java/postman/bottler/letter/exception/LetterExceptionHandler.java
  src/main/java/postman/bottler/letter/infra/LetterBoxJdbcRepository.java
  src/main/java/postman/bottler/letter/infra/LetterBoxRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/LetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/LetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/entity/LetterEntity.java
  src/main/java/postman/bottler/letter/infra/entity/ReplyLetterEntity.java
  src/main/java/postman/bottler/letter/service/LetterBoxRepository.java
  src/main/java/postman/bottler/letter/service/LetterBoxService.java
  src/main/java/postman/bottler/letter/service/LetterHelperService.java
  src/main/java/postman/bottler/letter/service/LetterRepository.java
  src/main/java/postman/bottler/letter/service/LetterService.java
  src/main/java/postman/bottler/letter/service/ReplyLetterRepository.java
  src/main/java/postman/bottler/letter/service/ReplyLetterService.java
  src/main/java/postman/bottler/scheduler/RecommendationScheduler.java
  src/main/java/postman/bottler/scheduler/SchedulerConfig.java
  src/main/resources/application.yml
Labels: feature

#137 Feature/#135 token status
  src/main/java/postman/bottler/config/SwaggerConfig.java
  src/main/java/postman/bottler/user/auth/JwtAccessDeniedHandler.java
  src/main/java/postman/bottler/user/auth/JwtAuthenticationEntryPoint.java
Labels: refactor

#143 fix: #141 도메인 허용 변경
  src/main/java/postman/bottler/config/SecurityConfig.java
Labels: hotfix

#121 refactor: 유저 정보 조회 response 변경
  src/main/java/postman/bottler/user/dto/response/UserResponseDTO.java
Labels: refactor

#122 Feature/#87 라벨 선착순 뽑기 로직 수정
  src/main/java/postman/bottler/label/controller/LabelController.java
  src/main/java/postman/bottler/label/infra/LabelRepositoryImpl.java
  src/main/java/postman/bottler/label/service/LabelService.java
Labels: refactor

#128 [Refactor/#119] batch job 제거
  build.gradle
  src/main/java/postman/bottler/batch/KeywordBatch.java
  src/main/java/postman/bottler/batch/NotificationWriter.java
  src/main/java/postman/bottler/batch/UnbanBatch.java
  src/main/java/postman/bottler/scheduler/SchedulerConfig.java
  src/main/java/postman/bottler/scheduler/UnbanScheduler.java
  src/main/java/postman/bottler/user/domain/Ban.java
  src/main/java/postman/bottler/user/infra/BanRepositoryImpl.java
  src/main/java/postman/bottler/user/infra/JpaBanRepository.java
  src/main/java/postman/bottler/user/infra/UserJpaRepository.java
  src/main/java/postman/bottler/user/infra/UserRepositoryImpl.java
  src/main/java/postman/bottler/user/infra/entity/BanEntity.java
  src/main/java/postman/bottler/user/service/BanRepository.java
  src/main/java/postman/bottler/user/service/BanService.java
  src/main/java/postman/bottler/user/service/UserRepository.java
  src/main/resources/application.yml
Labels: refactor

#140 fix: #136 로그인 한 유저가 해당 편지의 주인인지 확인하는 로직 추가
  src/main/java/postman/bottler/mapletter/dto/response/OneLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/dto/response/OneReplyLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/service/MapLetterService.java
Labels: fix

#147 feat: redis 배포 환경 설정 추가
  .github/workflows/cd.yml
  docker-compose/docker-compose.yml
Labels: feature

#142 Feature/#134 letter recommendation
  src/main/java/postman/bottler/global/response/code/ErrorStatus.java
  src/main/java/postman/bottler/keyword/controller/RecommendationController.java
  src/main/java/postman/bottler/keyword/service/RedisLetterService.java
  src/main/java/postman/bottler/letter/dto/LetterBoxDTO.java
  src/main/java/postman/bottler/letter/exception/LetterExceptionHandler.java
  src/main/java/postman/bottler/letter/exception/TempRecommendationsNotFoundException.java
  src/main/java/postman/bottler/letter/infra/LetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/service/LetterBoxService.java
  src/main/java/postman/bottler/letter/service/LetterHelperService.java
  src/main/java/postman/bottler/letter/service/LetterRepository.java
  src/main/java/postman/bottler/letter/service/LetterService.java
  src/main/java/postman/bottler/notification/dto/request/RecommendNotificationRequestDTO.java
  src/main/java/postman/bottler/scheduler/RecommendationScheduler.java
Labels: feature

#139 feat: 전체 유저 키워드 편지 도착 알림 기능 추가
  src/main/java/postman/bottler/notification/service/NotificationService.java
Labels: feature

#149 [Refactor/#148] 키워드 편지 추천 스케쥴러 로직 추가
  src/main/java/postman/bottler/scheduler/RecommendationScheduler.java
  src/main/java/postman/bottler/scheduler/SchedulerConfig.java
Labels: refactor

#150 Release: Merge develop into main for deployment
  .github/workflows/cd.yml
  build.gradle
  docker-compose/docker-compose.yml
  src/main/java/postman/bottler/batch/KeywordBatch.java
  src/main/java/postman/bottler/batch/NotificationWriter.java
  src/main/java/postman/bottler/batch/UnbanBatch.java
  src/main/java/postman/bottler/global/response/code/ErrorStatus.java
  src/main/java/postman/bottler/keyword/controller/RecommendationController.java
  src/main/java/postman/bottler/keyword/service/RedisLetterService.java
  src/main/java/postman/bottler/letter/dto/LetterBoxDTO.java
  src/main/java/postman/bottler/letter/exception/LetterExceptionHandler.java
  src/main/java/postman/bottler/letter/exception/TempRecommendationsNotFoundException.java
  src/main/java/postman/bottler/letter/infra/LetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/service/LetterBoxService.java
  src/main/java/postman/bottler/letter/service/LetterHelperService.java
  src/main/java/postman/bottler/letter/service/LetterRepository.java
  src/main/java/postman/bottler/letter/service/LetterService.java
  src/main/java/postman/bottler/mapletter/dto/response/OneLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/dto/response/OneReplyLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/service/MapLetterService.java
  src/main/java/postman/bottler/notification/dto/request/RecommendNotificationRequestDTO.java
  src/main/java/postman/bottler/notification/service/NotificationService.java
  src/main/java/postman/bottler/scheduler/RecommendationScheduler.java
  src/main/java/postman/bottler/scheduler/SchedulerConfig.java
  src/main/java/postman/bottler/scheduler/UnbanScheduler.java
  src/main/java/postman/bottler/user/domain/Ban.java
  src/main/java/postman/bottler/user/infra/BanRepositoryImpl.java
  src/main/java/postman/bottler/user/infra/JpaBanRepository.java
  src/main/java/postman/bottler/user/infra/UserJpaRepository.java
  src/main/java/postman/bottler/user/infra/UserRepositoryImpl.java
  src/main/java/postman/bottler/user/infra/entity/BanEntity.java
  src/main/java/postman/bottler/user/service/BanRepository.java
  src/main/java/postman/bottler/user/service/BanService.java
  src/main/java/postman/bottler/user/service/UserRepository.java
  src/main/resources/application.yml
Labels: CI-CD

#159 Feature/#152 리프레시 토큰 쿠키 sameSite 설정 추가
  src/main/java/postman/bottler/user/auth/CookieService.java
  src/main/java/postman/bottler/user/controller/AuthController.java
  src/main/java/postman/bottler/user/controller/OAuthController.java
  src/main/resources/application.yml
Labels: refactor

#162 [Refactor/#161] 키워드/타겟 편지 알림 조회 시 라벨 이미지 응답 추가
  src/main/java/postman/bottler/letter/service/LetterService.java
  src/main/java/postman/bottler/mapletter/infra/MapLetterRepositoryImpl.java
  src/main/java/postman/bottler/mapletter/service/MapLetterRepository.java
  src/main/java/postman/bottler/mapletter/service/MapLetterService.java
  src/main/java/postman/bottler/notification/controller/NotificationController.java
  src/main/java/postman/bottler/notification/domain/LetterNotification.java
  src/main/java/postman/bottler/notification/domain/Notification.java
  src/main/java/postman/bottler/notification/domain/Notifications.java
  src/main/java/postman/bottler/notification/dto/request/NotificationLabelRequestDTO.java
  src/main/java/postman/bottler/notification/dto/response/NotificationResponseDTO.java
  src/main/java/postman/bottler/notification/service/NotificationService.java
Labels: refactor

#174 Feature/#173 letters keyword frequent
  src/main/java/postman/bottler/keyword/controller/KeywordController.java
  src/main/java/postman/bottler/keyword/dto/response/FrequentKeywordsDTO.java
  src/main/java/postman/bottler/keyword/infra/LetterKeywordQueryDslRepository.java
  src/main/java/postman/bottler/keyword/infra/LetterKeywordRepositoryImpl.java
  src/main/java/postman/bottler/keyword/infra/entity/LetterKeywordEntity.java
  src/main/java/postman/bottler/keyword/service/AsyncRecommendationService.java
  src/main/java/postman/bottler/keyword/service/LetterKeywordRepository.java
  src/main/java/postman/bottler/keyword/service/LetterKeywordService.java
  src/main/java/postman/bottler/keyword/service/RedisLetterService.java
  src/main/java/postman/bottler/letter/infra/LetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/LetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/service/LetterRepository.java
  src/main/java/postman/bottler/letter/service/LetterService.java
  src/main/java/postman/bottler/notification/dto/request/RecommendNotificationRequestDTO.java
  src/main/resources/application.yml
Labels: feature

#175 CI-CD
  src/main/java/postman/bottler/keyword/controller/KeywordController.java
  src/main/java/postman/bottler/keyword/dto/response/FrequentKeywordsDTO.java
  src/main/java/postman/bottler/keyword/infra/LetterKeywordQueryDslRepository.java
  src/main/java/postman/bottler/keyword/infra/LetterKeywordRepositoryImpl.java
  src/main/java/postman/bottler/keyword/infra/entity/LetterKeywordEntity.java
  src/main/java/postman/bottler/keyword/service/AsyncRecommendationService.java
  src/main/java/postman/bottler/keyword/service/LetterKeywordRepository.java
  src/main/java/postman/bottler/keyword/service/LetterKeywordService.java
  src/main/java/postman/bottler/keyword/service/RedisLetterService.java
  src/main/java/postman/bottler/letter/infra/LetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/LetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/service/LetterRepository.java
  src/main/java/postman/bottler/letter/service/LetterService.java
  src/main/java/postman/bottler/notification/dto/request/RecommendNotificationRequestDTO.java
  src/main/resources/application.yml
Labels: CI-CD

#172 fix: 신고 테스트 코드 컴파일 오류 수정
  src/test/java/postman/bottler/complaint/domain/ComplaintsTest.java
  src/test/java/postman/bottler/complaint/infra/KeywordComplaintRepositoryTest.java
  src/test/java/postman/bottler/complaint/infra/MapComplaintRepositoryTest.java
  src/test/java/postman/bottler/complaint/service/ComplaintServiceTest.java
  src/test/resources/application.yml
Labels: fix

#176 Feature/#165 : 알림 의존성 제거 및 타 도메인 알림 요청 추가
  src/main/java/postman/bottler/complaint/service/ComplaintService.java
  src/main/java/postman/bottler/letter/service/ReplyLetterService.java
  src/main/java/postman/bottler/mapletter/infra/MapLetterRepositoryImpl.java
  src/main/java/postman/bottler/mapletter/service/MapLetterRepository.java
  src/main/java/postman/bottler/mapletter/service/MapLetterService.java
  src/main/java/postman/bottler/notification/controller/NotificationController.java
  src/main/java/postman/bottler/notification/domain/LetterNotification.java
  src/main/java/postman/bottler/notification/domain/Notification.java
  src/main/java/postman/bottler/notification/domain/Notifications.java
  src/main/java/postman/bottler/notification/dto/request/NotificationRequestDTO.java
  src/main/java/postman/bottler/notification/infra/NotificationHashKey.java
  src/main/java/postman/bottler/notification/infra/RedisNotification.java
  src/main/java/postman/bottler/notification/service/NotificationService.java
  src/main/java/postman/bottler/user/service/UserService.java
  src/test/java/postman/bottler/notification/domain/LetterNotificationTest.java
  src/test/java/postman/bottler/notification/domain/NotificationTest.java
  src/test/java/postman/bottler/notification/service/NotificationServiceTest.java
Labels: refactor

#178 refactor: 액세스 토큰 유효 시간 변경
  src/main/resources/application.yml
Labels: refactor

#177 Develop To Main
  src/main/java/postman/bottler/complaint/service/ComplaintService.java
  src/main/java/postman/bottler/letter/service/ReplyLetterService.java
  src/main/java/postman/bottler/mapletter/infra/MapLetterRepositoryImpl.java
  src/main/java/postman/bottler/mapletter/service/MapLetterRepository.java
  src/main/java/postman/bottler/mapletter/service/MapLetterService.java
  src/main/java/postman/bottler/notification/controller/NotificationController.java
  src/main/java/postman/bottler/notification/domain/LetterNotification.java
  src/main/java/postman/bottler/notification/domain/Notification.java
  src/main/java/postman/bottler/notification/domain/Notifications.java
  src/main/java/postman/bottler/notification/dto/request/NotificationRequestDTO.java
  src/main/java/postman/bottler/notification/infra/NotificationHashKey.java
  src/main/java/postman/bottler/notification/infra/RedisNotification.java
  src/main/java/postman/bottler/notification/service/NotificationService.java
  src/main/java/postman/bottler/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/postman/bottler/complaint/domain/ComplaintsTest.java
  src/test/java/postman/bottler/complaint/infra/KeywordComplaintRepositoryTest.java
  src/test/java/postman/bottler/complaint/infra/MapComplaintRepositoryTest.java
  src/test/java/postman/bottler/complaint/service/ComplaintServiceTest.java
  src/test/java/postman/bottler/notification/domain/LetterNotificationTest.java
  src/test/java/postman/bottler/notification/domain/NotificationTest.java
  src/test/java/postman/bottler/notification/service/NotificationServiceTest.java
  src/test/resources/application.yml
Labels: CI-CD

#180 feat: 사용자 알림 기기 등록 시, 중복 체크 기능 추가
  src/main/java/postman/bottler/global/response/code/ErrorStatus.java
  src/main/java/postman/bottler/notification/exception/DuplicateTokenException.java
  src/main/java/postman/bottler/notification/exception/NotificationExceptionHandler.java
  src/main/java/postman/bottler/notification/infra/JpaSubscriptionRepository.java
  src/main/java/postman/bottler/notification/infra/SubscriptionRepositoryImpl.java
  src/main/java/postman/bottler/notification/service/SubscriptionRepository.java
  src/main/java/postman/bottler/notification/service/SubscriptionService.java
Labels: feature

#190 refactor: 정지 유저 접근 권한 제한
  src/main/java/postman/bottler/config/SecurityConfig.java
  src/main/java/postman/bottler/scheduler/SchedulerConfig.java
Labels: refactor

#207 CI-CD
  src/main/java/postman/bottler/user/service/UserService.java
Labels: CI-CD

#209 feat: isReplied 키워드 답장 편지 상세에 추가
  src/main/java/postman/bottler/letter/controller/ReplyLetterController.java
  src/main/java/postman/bottler/letter/dto/response/ReplyLetterDetailResponseDTO.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/service/ReplyLetterRepository.java
  src/main/java/postman/bottler/letter/service/ReplyLetterService.java
Labels: feature

#210 CI-CD
  src/main/java/postman/bottler/letter/controller/ReplyLetterController.java
  src/main/java/postman/bottler/letter/dto/response/ReplyLetterDetailResponseDTO.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/service/ReplyLetterRepository.java
  src/main/java/postman/bottler/letter/service/ReplyLetterService.java
Labels: CI-CD

#212 hotfix: 저장된 편지의 ID가 들어가도록 수정
  src/main/java/postman/bottler/mapletter/service/MapLetterService.java
Labels: hotfix

#213 develop to main
  src/main/java/postman/bottler/mapletter/service/MapLetterService.java
Labels: CI-CD

#215 refactor: JPA Entity 편지 content text 타입으로 수정
  src/main/java/postman/bottler/letter/infra/entity/LetterEntity.java
  src/main/java/postman/bottler/letter/infra/entity/ReplyLetterEntity.java
  src/main/java/postman/bottler/mapletter/infra/entity/MapLetterEntity.java
  src/main/java/postman/bottler/mapletter/infra/entity/ReplyMapLetterEntity.java
Labels: refactor

#217 fix: 편지 추천 검증 조건 변경
  src/main/java/postman/bottler/keyword/service/RedisLetterService.java
  src/main/java/postman/bottler/scheduler/RecommendationScheduler.java
Labels: fix

#218 CI-CD
  src/main/java/postman/bottler/keyword/service/RedisLetterService.java
  src/main/java/postman/bottler/letter/infra/entity/LetterEntity.java
  src/main/java/postman/bottler/letter/infra/entity/ReplyLetterEntity.java
  src/main/java/postman/bottler/mapletter/infra/entity/MapLetterEntity.java
  src/main/java/postman/bottler/mapletter/infra/entity/ReplyMapLetterEntity.java
  src/main/java/postman/bottler/scheduler/RecommendationScheduler.java
Labels: CI-CD

#220 feat: 키워드 편지 테스트 api 구현
  src/main/java/postman/bottler/keyword/controller/RecommendationController.java
Labels: feature

#221 CI-CD
  src/main/java/postman/bottler/keyword/controller/RecommendationController.java
Labels: CI-CD

#226 Refactor/#222 keyword letter
  src/main/java/postman/bottler/keyword/infra/LetterKeywordJdbcRepository.java
  src/main/java/postman/bottler/keyword/infra/LetterKeywordRepositoryImpl.java
  src/main/java/postman/bottler/keyword/service/AsyncRecommendationService.java
  src/main/java/postman/bottler/keyword/service/LetterKeywordRepository.java
  src/main/java/postman/bottler/keyword/service/LetterKeywordService.java
  src/main/java/postman/bottler/keyword/service/RedisLetterService.java
  src/main/java/postman/bottler/letter/controller/LetterBoxController.java
  src/main/java/postman/bottler/letter/controller/LetterController.java
  src/main/java/postman/bottler/letter/controller/ReplyLetterController.java
  src/main/java/postman/bottler/letter/dto/LetterDeleteRequests.java
  src/main/java/postman/bottler/letter/dto/response/LetterDetailResponseDTO.java
  src/main/java/postman/bottler/letter/dto/response/LetterRecommendSummaryResponseDTO.java
  src/main/java/postman/bottler/letter/dto/response/LetterResponseDTO.java
  src/main/java/postman/bottler/letter/dto/response/LetterSummaryResponseDTO.java
  src/main/java/postman/bottler/letter/dto/response/ReplyLetterSummaryResponseDTO.java
  src/main/java/postman/bottler/letter/infra/LetterBoxJdbcRepository.java
  src/main/java/postman/bottler/letter/infra/LetterBoxJpaRepository.java
  src/main/java/postman/bottler/letter/infra/LetterBoxQueryRepository.java
  src/main/java/postman/bottler/letter/infra/LetterBoxRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/LetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/LetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/processor/LetterDeletionContext.java
  src/main/java/postman/bottler/letter/processor/LetterTypeProcessor.java
  src/main/java/postman/bottler/letter/service/BlockService.java
  src/main/java/postman/bottler/letter/service/DeleteManagerService.java
  src/main/java/postman/bottler/letter/service/LetterBoxRepository.java
  src/main/java/postman/bottler/letter/service/LetterBoxService.java
  src/main/java/postman/bottler/letter/service/LetterDeletionService.java
  src/main/java/postman/bottler/letter/service/LetterFacadeService.java
  src/main/java/postman/bottler/letter/service/LetterRepository.java
  src/main/java/postman/bottler/letter/service/LetterService.java
  src/main/java/postman/bottler/letter/service/LetterServiceRedis.java
  src/main/java/postman/bottler/letter/service/ReplyLetterRepository.java
  src/main/java/postman/bottler/letter/service/ReplyLetterService.java
Labels: refactor

#229 Chore/#227 알림/신고 패키지 구조 변경
  src/main/java/postman/bottler/complaint/application/repository/ComplaintRepository.java
  src/main/java/postman/bottler/complaint/application/repository/KeywordComplaintRepository.java
  src/main/java/postman/bottler/complaint/application/repository/KeywordReplyComplaintRepository.java
  src/main/java/postman/bottler/complaint/application/repository/MapComplaintRepository.java
  src/main/java/postman/bottler/complaint/application/repository/MapReplyComplaintRepository.java
  src/main/java/postman/bottler/complaint/application/service/ComplaintService.java
  src/main/java/postman/bottler/complaint/infra/keyword/KeywordComplaintRepositoryImpl.java
  src/main/java/postman/bottler/complaint/infra/keyword/KeywordReplyComplaintRepositoryImpl.java
  src/main/java/postman/bottler/complaint/infra/map/MapComplaintRepositoryImpl.java
  src/main/java/postman/bottler/complaint/infra/map/MapReplyComplaintRepositoryImpl.java
  src/main/java/postman/bottler/complaint/presentation/ComplaintController.java
  src/main/java/postman/bottler/letter/service/ReplyLetterService.java
  src/main/java/postman/bottler/mapletter/service/MapLetterService.java
  src/main/java/postman/bottler/notification/application/PushNotificationProvider.java
  src/main/java/postman/bottler/notification/application/repository/NotificationRepository.java
  src/main/java/postman/bottler/notification/application/repository/SubscriptionRepository.java
  src/main/java/postman/bottler/notification/application/service/NotificationService.java
  src/main/java/postman/bottler/notification/application/service/SubscriptionService.java
  src/main/java/postman/bottler/notification/infra/FirebasePushProvider.java
  src/main/java/postman/bottler/notification/infra/RedisNotificationRepositoryImpl.java
  src/main/java/postman/bottler/notification/infra/SubscriptionRepositoryImpl.java
  src/main/java/postman/bottler/notification/presentation/NotificationController.java
  src/main/java/postman/bottler/scheduler/RecommendationScheduler.java
  src/main/java/postman/bottler/user/service/UserService.java
  src/test/java/postman/bottler/complaint/application/ComplaintServiceTest.java
  src/test/java/postman/bottler/complaint/infra/KeywordComplaintRepositoryTest.java
  src/test/java/postman/bottler/complaint/infra/MapComplaintRepositoryTest.java
  src/test/java/postman/bottler/notification/application/NotificationServiceTest.java
  src/test/java/postman/bottler/notification/application/SubscriptionServiceTest.java
Labels: chore

#231 chore: #227 map letter 패키지 구조 변경
  src/main/java/postman/bottler/complaint/application/service/ComplaintService.java
  src/main/java/postman/bottler/mapletter/application/BlockMapLetterType.java
  src/main/java/postman/bottler/mapletter/application/repository/MapLetterArchiveRepository.java
  src/main/java/postman/bottler/mapletter/application/repository/MapLetterRepository.java
  src/main/java/postman/bottler/mapletter/application/repository/PaperRepository.java
  src/main/java/postman/bottler/mapletter/application/repository/ReplyMapLetterRepository.java
  src/main/java/postman/bottler/mapletter/application/service/MapLetterService.java
  src/main/java/postman/bottler/mapletter/application/service/PaperService.java
  src/main/java/postman/bottler/mapletter/controller/MapLetterService.java
  src/main/java/postman/bottler/mapletter/infra/MapLetterArchiveRepositoryImpl.java
  src/main/java/postman/bottler/mapletter/infra/MapLetterRepositoryImpl.java
  src/main/java/postman/bottler/mapletter/infra/PaperRepositoryImpl.java
  src/main/java/postman/bottler/mapletter/infra/ReplyMapLetterRepositoryImpl.java
  src/main/java/postman/bottler/mapletter/presentation/MapLetterController.java
  src/main/java/postman/bottler/mapletter/presentation/PaperController.java
  src/main/java/postman/bottler/reply/service/ReplyService.java
  src/test/java/postman/bottler/mapletter/service/MapLetterServiceTest.java
  src/test/java/postman/bottler/mapletter/service/PaperServiceTest.java
Labels: chore
