Repository prgrms-web-devcourse-final-project/WEB1_1_Postman_BE, pull requests merged in 2025-01, with the labels that each got.

#240 Feature/#239 redis volume
  docker-compose/docker-compose.yml
  src/main/resources/application.yml
Labels: feature

#243 refactor: #242 지도 편지 에러 리팩토링
  src/main/java/postman/bottler/mapletter/exception/MapLetterExceptionHandler.java
Labels: refactor

#244 Refactor/#242 : 알림/신고 예외 코드 응답 수정
  src/main/java/postman/bottler/complaint/exception/ComplaintExceptionHandler.java
  src/main/java/postman/bottler/notification/exception/NotificationExceptionHandler.java
Labels: refactor

#236 Test/#228 알림 테스트 코드 추가
  src/main/java/postman/bottler/notification/application/dto/response/NotificationResponseDTO.java
  src/main/java/postman/bottler/notification/application/service/NotificationService.java
  src/main/java/postman/bottler/notification/domain/LetterNotification.java
  src/main/java/postman/bottler/notification/domain/Notification.java
  src/main/java/postman/bottler/notification/domain/Notifications.java
  src/main/java/postman/bottler/notification/domain/Subscriptions.java
  src/test/java/postman/bottler/notification/application/NotificationServiceTest.java
  src/test/java/postman/bottler/notification/domain/NotificationTest.java
  src/test/java/postman/bottler/notification/domain/NotificationTypeTest.java
  src/test/java/postman/bottler/notification/domain/NotificationsTest.java
  src/test/java/postman/bottler/notification/domain/SubscriptionTest.java
  src/test/java/postman/bottler/notification/domain/SubscriptionsTest.java
  src/test/java/postman/bottler/notification/infra/FirebaseMessageMapperTest.java
  src/test/java/postman/bottler/notification/infra/SubscriptionRepositoryImplTest.java
Labels: test

#247 Feature/#123 유저 테스트 코드 추가
  src/test/java/postman/bottler/user/application/BanServiceTest.java
  src/test/java/postman/bottler/user/application/EmailServiceTest.java
  src/test/java/postman/bottler/user/application/KakaoServiceTest.java
  src/test/java/postman/bottler/user/application/UserServiceTest.java
  src/test/java/postman/bottler/user/domain/BanTest.java
  src/test/java/postman/bottler/user/domain/EmailCodeTest.java
  src/test/java/postman/bottler/user/domain/UserTest.java
Labels: test

#249 Feature/#248: request/response 로그 추가
  src/main/java/postman/bottler/global/aop/LogAspect.java
  src/main/java/postman/bottler/global/response/ApiResponse.java
Labels: feature

#252 Fix/#251 2차 스프린트 기간 지도 편지 api 수정
  src/main/java/postman/bottler/mapletter/application/dto/FindReceivedMapLetterDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/request/DeleteMapLettersRequestDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/request/DeleteMapLettersV1RequestDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/response/FindAllReceivedLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/response/FindAllReceivedReplyLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/response/FindAllSentMapLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/response/FindAllSentReplyMapLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/response/FindMapLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/response/FindReceivedMapLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/application/repository/MapLetterRepository.java
  src/main/java/postman/bottler/mapletter/application/service/MapLetterService.java
  src/main/java/postman/bottler/mapletter/domain/MapLetter.java
  src/main/java/postman/bottler/mapletter/exception/MapLetterExceptionHandler.java
  src/main/java/postman/bottler/mapletter/infra/MapLetterJpaRepository.java
  src/main/java/postman/bottler/mapletter/infra/MapLetterRepositoryImpl.java
  src/main/java/postman/bottler/mapletter/infra/entity/MapLetterEntity.java
  src/main/java/postman/bottler/mapletter/presentation/MapLetterController.java
Labels: fix

#255 Feature/#234 letter test
  .github/workflows/ci.yml
  build.gradle
  src/main/java/postman/bottler/global/response/code/ErrorStatus.java
  src/main/java/postman/bottler/keyword/infra/entity/KeywordEntity.java
  src/main/java/postman/bottler/letter/exception/InvalidInputException.java
  src/main/java/postman/bottler/letter/exception/LetterExceptionHandler.java
  src/test/java/postman/bottler/BottlerApplicationTests.java
  src/test/java/postman/bottler/EnvTest.java
  src/test/java/postman/bottler/H2ConnectionTest.java
  src/test/java/postman/bottler/TestBase.java
  src/test/java/postman/bottler/keyword/application/service/AsyncRecommendationServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/KeywordServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/LetterKeywordServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/RecommendServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/RedisLetterServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/UserKeywordServiceTest.java
  src/test/java/postman/bottler/keyword/domain/KeywordTest.java
  src/test/java/postman/bottler/keyword/domain/LetterKeywordTest.java
  src/test/java/postman/bottler/keyword/domain/UserKeywordTest.java
  src/test/java/postman/bottler/keyword/infra/KeywordRepositoryImplTest.java
  src/test/java/postman/bottler/keyword/infra/LetterKeywordJdbcRepositoryTest.java
  src/test/java/postman/bottler/keyword/infra/LetterKeywordRepositoryImplTest.java
  src/test/java/postman/bottler/keyword/infra/UserKeywordJdbcRepositoryTest.java
  src/test/java/postman/bottler/keyword/infra/UserKeywordJpaRepositoryTest.java
  src/test/java/postman/bottler/keyword/infra/UserKeywordRepositoryImplTest.java
  src/test/java/postman/bottler/letter/application/service/LetterBoxServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterDeletionServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterFacadeServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterServiceTest.java
  src/test/java/postman/bottler/letter/application/service/ReplyLetterServiceTest.java
  src/test/java/postman/bottler/letter/domain/LetterBoxTest.java
  src/test/java/postman/bottler/letter/domain/LetterTest.java
  src/test/java/postman/bottler/letter/domain/ReplyLetterTest.java
  src/test/java/postman/bottler/letter/infra/LetterBoxJdbcRepositoryTest.java
  src/test/java/postman/bottler/letter/infra/LetterBoxQueryRepositoryTest.java
  src/test/java/postman/bottler/letter/infra/LetterBoxRepositoryImplTest.java
  src/test/java/postman/bottler/letter/infra/LetterJpaRepositoryTest.java
  src/test/java/postman/bottler/letter/infra/LetterRepositoryImplTest.java
  src/test/java/postman/bottler/letter/infra/ReplyLetterJpaRepositoryTest.java
  src/test/java/postman/bottler/letter/infra/ReplyLetterRepositoryImplTest.java
  src/test/java/postman/bottler/scheduler/RecommendationSchedulerTest.java
Labels: test

#256 Chore/#254 actuator 모니터링 설정 추가
  build.gradle
  src/main/java/postman/bottler/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: chore

#257 2차 스프린트 배포
  .github/workflows/ci.yml
  build.gradle
  src/main/java/postman/bottler/config/SecurityConfig.java
  src/main/java/postman/bottler/global/response/code/ErrorStatus.java
  src/main/java/postman/bottler/keyword/infra/entity/KeywordEntity.java
  src/main/java/postman/bottler/letter/exception/InvalidInputException.java
  src/main/java/postman/bottler/letter/exception/LetterExceptionHandler.java
  src/main/java/postman/bottler/mapletter/application/dto/FindReceivedMapLetterDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/request/DeleteMapLettersRequestDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/request/DeleteMapLettersV1RequestDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/response/FindAllReceivedLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/response/FindAllReceivedReplyLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/response/FindAllSentMapLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/response/FindAllSentReplyMapLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/response/FindMapLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/response/FindReceivedMapLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/application/repository/MapLetterRepository.java
  src/main/java/postman/bottler/mapletter/application/service/MapLetterService.java
  src/main/java/postman/bottler/mapletter/domain/MapLetter.java
  src/main/java/postman/bottler/mapletter/exception/MapLetterExceptionHandler.java
  src/main/java/postman/bottler/mapletter/infra/MapLetterJpaRepository.java
  src/main/java/postman/bottler/mapletter/infra/MapLetterRepositoryImpl.java
  src/main/java/postman/bottler/mapletter/infra/entity/MapLetterEntity.java
  src/main/java/postman/bottler/mapletter/presentation/MapLetterController.java
  src/main/resources/application.yml
  src/test/java/postman/bottler/BottlerApplicationTests.java
  src/test/java/postman/bottler/EnvTest.java
  src/test/java/postman/bottler/H2ConnectionTest.java
  src/test/java/postman/bottler/TestBase.java
  src/test/java/postman/bottler/keyword/application/service/AsyncRecommendationServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/KeywordServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/LetterKeywordServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/RecommendServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/RedisLetterServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/UserKeywordServiceTest.java
  src/test/java/postman/bottler/keyword/domain/KeywordTest.java
  src/test/java/postman/bottler/keyword/domain/LetterKeywordTest.java
  src/test/java/postman/bottler/keyword/domain/UserKeywordTest.java
  src/test/java/postman/bottler/keyword/infra/KeywordRepositoryImplTest.java
  src/test/java/postman/bottler/keyword/infra/LetterKeywordJdbcRepositoryTest.java
  src/test/java/postman/bottler/keyword/infra/LetterKeywordRepositoryImplTest.java
  src/test/java/postman/bottler/keyword/infra/UserKeywordJdbcRepositoryTest.java
  src/test/java/postman/bottler/keyword/infra/UserKeywordJpaRepositoryTest.java
  src/test/java/postman/bottler/keyword/infra/UserKeywordRepositoryImplTest.java
  src/test/java/postman/bottler/letter/application/service/LetterBoxServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterDeletionServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterFacadeServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterServiceTest.java
  src/test/java/postman/bottler/letter/application/service/ReplyLetterServiceTest.java
  src/test/java/postman/bottler/letter/domain/LetterBoxTest.java
  src/test/java/postman/bottler/letter/domain/LetterTest.java
  src/test/java/postman/bottler/letter/domain/ReplyLetterTest.java
  src/test/java/postman/bottler/letter/infra/LetterBoxJdbcRepositoryTest.java
  src/test/java/postman/bottler/letter/infra/LetterBoxQueryRepositoryTest.java
  src/test/java/postman/bottler/letter/infra/LetterBoxRepositoryImplTest.java
  src/test/java/postman/bottler/letter/infra/LetterJpaRepositoryTest.java
  src/test/java/postman/bottler/letter/infra/LetterRepositoryImplTest.java
  src/test/java/postman/bottler/letter/infra/ReplyLetterJpaRepositoryTest.java
  src/test/java/postman/bottler/letter/infra/ReplyLetterRepositoryImplTest.java
  src/test/java/postman/bottler/scheduler/RecommendationSchedulerTest.java
Labels: fix, test, chore

#262 Chore/#258 yml being hidden
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: chore

#264 Refactor/#263 improve async recommendation
  src/main/java/postman/bottler/keyword/application/service/AsyncRecommendationService.java
  src/main/java/postman/bottler/keyword/application/service/RedisLetterService.java
  src/main/java/postman/bottler/keyword/presentation/RecommendationController.java
  src/main/java/postman/bottler/letter/exception/LetterExceptionHandler.java
  src/main/java/postman/bottler/scheduler/RecommendationScheduler.java
Labels: refactor

#261 Feature/#259 : 읽지 않은 알림 개수 조회 기능 추가
  src/main/java/postman/bottler/notification/application/dto/response/UnreadNotificationResponseDTO.java
  src/main/java/postman/bottler/notification/application/service/NotificationService.java
  src/main/java/postman/bottler/notification/domain/Notifications.java
  src/main/java/postman/bottler/notification/presentation/NotificationController.java
  src/test/java/postman/bottler/notification/application/NotificationServiceTest.java
  src/test/java/postman/bottler/notification/domain/NotificationsTest.java
Labels: feature

#267 Feature/#265 add reply status to letter details
  src/main/java/postman/bottler/letter/application/dto/response/LetterDetailResponseDTO.java
  src/main/java/postman/bottler/letter/application/service/LetterFacadeService.java
  src/main/java/postman/bottler/letter/application/service/ReplyLetterService.java
Labels: feature

#268 Fix / 편지에 대한 답장 알림시 답장된 편지 Id가 아닌 편지 Id가 제공되는 문제 수정
  src/main/java/postman/bottler/letter/application/service/ReplyLetterService.java
Labels: fix

#274 chore: 모니터링 포트 추가
  docker-compose/docker-compose.yml
Labels: chore

#275 ci-cd : develop to main
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  docker-compose/docker-compose.yml
  src/main/java/postman/bottler/keyword/application/service/AsyncRecommendationService.java
  src/main/java/postman/bottler/keyword/application/service/RedisLetterService.java
  src/main/java/postman/bottler/keyword/presentation/RecommendationController.java
  src/main/java/postman/bottler/letter/application/dto/response/LetterDetailResponseDTO.java
  src/main/java/postman/bottler/letter/application/service/LetterFacadeService.java
  src/main/java/postman/bottler/letter/application/service/ReplyLetterService.java
  src/main/java/postman/bottler/letter/exception/LetterExceptionHandler.java
  src/main/java/postman/bottler/notification/application/dto/response/UnreadNotificationResponseDTO.java
  src/main/java/postman/bottler/notification/application/service/NotificationService.java
  src/main/java/postman/bottler/notification/domain/Notifications.java
  src/main/java/postman/bottler/notification/presentation/NotificationController.java
  src/main/java/postman/bottler/scheduler/RecommendationScheduler.java
  src/main/resources/application.yml
  src/test/java/postman/bottler/notification/application/NotificationServiceTest.java
  src/test/java/postman/bottler/notification/domain/NotificationsTest.java
  src/test/resources/application.yml
Labels: CI-CD

#277 chore: yml base64 디코딩 추가
  .github/workflows/cd.yml
Labels: CI-CD

#278 ci-cd: develop to main
  .github/workflows/cd.yml
Labels: CI-CD

#272 Refactor/#269 keyword letter
  src/main/java/postman/bottler/complaint/application/service/ComplaintService.java
  src/main/java/postman/bottler/keyword/application/service/AsyncRecommendationService.java
  src/main/java/postman/bottler/keyword/application/service/RedisLetterService.java
  src/main/java/postman/bottler/keyword/util/RedisLetterKeyUtil.java
  src/main/java/postman/bottler/letter/application/repository/LetterBoxRepository.java
  src/main/java/postman/bottler/letter/application/repository/LetterRepository.java
  src/main/java/postman/bottler/letter/application/repository/ReplyLetterRepository.java
  src/main/java/postman/bottler/letter/application/service/LetterBoxService.java
  src/main/java/postman/bottler/letter/application/service/LetterDeletionService.java
  src/main/java/postman/bottler/letter/application/service/LetterFacadeService.java
  src/main/java/postman/bottler/letter/application/service/LetterService.java
  src/main/java/postman/bottler/letter/application/service/ReplyLetterService.java
  src/main/java/postman/bottler/letter/domain/Letter.java
  src/main/java/postman/bottler/letter/domain/LetterBox.java
  src/main/java/postman/bottler/letter/domain/ReplyLetter.java
  src/main/java/postman/bottler/letter/exception/BaseLetterValidationException.java
  src/main/java/postman/bottler/letter/exception/InvalidDeleteRequestException.java
  src/main/java/postman/bottler/letter/exception/InvalidLetterRequestException.java
  src/main/java/postman/bottler/letter/exception/InvalidPageRequestException.java
  src/main/java/postman/bottler/letter/exception/InvalidReplyLetterRequestException.java
  src/main/java/postman/bottler/letter/exception/LetterExceptionHandler.java
  src/main/java/postman/bottler/letter/exception/LetterValidationException.java
  src/main/java/postman/bottler/letter/infra/LetterBoxQueryRepository.java
  src/main/java/postman/bottler/letter/infra/LetterBoxRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/LetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/presentation/LetterBoxController.java
  src/main/java/postman/bottler/letter/presentation/LetterController.java
  src/main/java/postman/bottler/letter/presentation/ReplyLetterController.java
  src/main/java/postman/bottler/letter/presentation/annotation/LetterValidationMetaData.java
  src/main/java/postman/bottler/letter/processor/LetterTypeProcessor.java
  src/main/java/postman/bottler/letter/utiil/ValidationAspect.java
  src/main/java/postman/bottler/letter/utiil/ValidationUtil.java
  src/test/java/postman/bottler/complaint/application/ComplaintServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/AsyncRecommendationServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/RedisLetterServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterBoxServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterFacadeServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterServiceTest.java
  src/test/java/postman/bottler/letter/application/service/ReplyLetterServiceTest.java
  src/test/java/postman/bottler/letter/infra/LetterBoxQueryRepositoryTest.java
  src/test/java/postman/bottler/letter/infra/LetterBoxRepositoryImplTest.java
  src/test/java/postman/bottler/letter/infra/LetterRepositoryImplTest.java
  src/test/java/postman/bottler/letter/infra/ReplyLetterJpaRepositoryTest.java
  src/test/java/postman/bottler/letter/infra/ReplyLetterRepositoryImplTest.java
Labels: refactor

#280 Fix/#279 3차 스프린트 기간 지도편지 수정
  src/main/java/postman/bottler/mapletter/application/dto/request/DeleteArchivedLettersRequestDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/request/DeleteArchivedLettersRequestDTOV1.java
  src/main/java/postman/bottler/mapletter/application/dto/response/OneLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/application/repository/MapLetterArchiveRepository.java
  src/main/java/postman/bottler/mapletter/application/service/MapLetterService.java
  src/main/java/postman/bottler/mapletter/infra/MapLetterArchiveRepositoryImpl.java
  src/main/java/postman/bottler/mapletter/presentation/MapLetterController.java
Labels: fix
