Repository prgrms-web-devcourse-final-project/WEB1_1_Postman_BE, pull requests merged in 2025-02, with the labels that each got.

#281 3차 스프린트 기간 배포
  src/main/java/postman/bottler/complaint/application/service/ComplaintService.java
  src/main/java/postman/bottler/keyword/application/service/AsyncRecommendationService.java
  src/main/java/postman/bottler/keyword/application/service/RedisLetterService.java
  src/main/java/postman/bottler/keyword/util/RedisLetterKeyUtil.java
  src/main/java/postman/bottler/letter/application/repository/LetterBoxRepository.java
  src/main/java/postman/bottler/letter/application/repository/LetterRepository.java
  src/main/java/postman/bottler/letter/application/repository/ReplyLetterRepository.java
  src/main/java/postman/bottler/letter/application/service/LetterBoxService.java
  src/main/java/postman/bottler/letter/application/service/LetterDeletionService.java
  src/main/java/postman/bottler/letter/application/service/LetterFacadeService.java
  src/main/java/postman/bottler/letter/application/service/LetterService.java
  src/main/java/postman/bottler/letter/application/service/ReplyLetterService.java
  src/main/java/postman/bottler/letter/domain/Letter.java
  src/main/java/postman/bottler/letter/domain/LetterBox.java
  src/main/java/postman/bottler/letter/domain/ReplyLetter.java
  src/main/java/postman/bottler/letter/exception/BaseLetterValidationException.java
  src/main/java/postman/bottler/letter/exception/InvalidDeleteRequestException.java
  src/main/java/postman/bottler/letter/exception/InvalidLetterRequestException.java
  src/main/java/postman/bottler/letter/exception/InvalidPageRequestException.java
  src/main/java/postman/bottler/letter/exception/InvalidReplyLetterRequestException.java
  src/main/java/postman/bottler/letter/exception/LetterExceptionHandler.java
  src/main/java/postman/bottler/letter/exception/LetterValidationException.java
  src/main/java/postman/bottler/letter/infra/LetterBoxQueryRepository.java
  src/main/java/postman/bottler/letter/infra/LetterBoxRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/LetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/presentation/LetterBoxController.java
  src/main/java/postman/bottler/letter/presentation/LetterController.java
  src/main/java/postman/bottler/letter/presentation/ReplyLetterController.java
  src/main/java/postman/bottler/letter/presentation/annotation/LetterValidationMetaData.java
  src/main/java/postman/bottler/letter/processor/LetterTypeProcessor.java
  src/main/java/postman/bottler/letter/utiil/ValidationAspect.java
  src/main/java/postman/bottler/letter/utiil/ValidationUtil.java
  src/main/java/postman/bottler/mapletter/application/dto/request/DeleteArchivedLettersRequestDTO.java
  src/main/java/postman/bottler/mapletter/application/dto/request/DeleteArchivedLettersRequestDTOV1.java
  src/main/java/postman/bottler/mapletter/application/dto/response/OneLetterResponseDTO.java
  src/main/java/postman/bottler/mapletter/application/repository/MapLetterArchiveRepository.java
  src/main/java/postman/bottler/mapletter/application/service/MapLetterService.java
  src/main/java/postman/bottler/mapletter/infra/MapLetterArchiveRepositoryImpl.java
  src/main/java/postman/bottler/mapletter/presentation/MapLetterController.java
  src/test/java/postman/bottler/complaint/application/ComplaintServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/AsyncRecommendationServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/RedisLetterServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterBoxServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterFacadeServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterServiceTest.java
  src/test/java/postman/bottler/letter/application/service/ReplyLetterServiceTest.java
  src/test/java/postman/bottler/letter/infra/LetterBoxQueryRepositoryTest.java
  src/test/java/postman/bottler/letter/infra/LetterBoxRepositoryImplTest.java
  src/test/java/postman/bottler/letter/infra/LetterRepositoryImplTest.java
  src/test/java/postman/bottler/letter/infra/ReplyLetterJpaRepositoryTest.java
  src/test/java/postman/bottler/letter/infra/ReplyLetterRepositoryImplTest.java
Labels: feature, fix

#282 Refactor/#270 keywords
  src/main/java/postman/bottler/keyword/application/repository/UserKeywordRepository.java
  src/main/java/postman/bottler/keyword/application/service/AsyncRecommendationService.java
  src/main/java/postman/bottler/keyword/application/service/RedisLetterService.java
  src/main/java/postman/bottler/keyword/application/service/UserKeywordService.java
  src/main/java/postman/bottler/keyword/infra/LetterKeywordJdbcRepository.java
  src/main/java/postman/bottler/keyword/infra/UserKeywordJdbcRepository.java
  src/main/java/postman/bottler/keyword/infra/UserKeywordJpaRepository.java
  src/main/java/postman/bottler/keyword/infra/UserKeywordRepositoryImpl.java
  src/main/java/postman/bottler/keyword/presentation/KeywordController.java
  src/main/java/postman/bottler/keyword/presentation/RecommendationController.java
  src/main/java/postman/bottler/keyword/util/RedisLetterKeyUtil.java
  src/main/java/postman/bottler/letter/application/service/LetterFacadeService.java
  src/test/java/postman/bottler/keyword/application/service/AsyncRecommendationServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/RedisLetterServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/UserKeywordServiceTest.java
  src/test/java/postman/bottler/keyword/infra/UserKeywordJpaRepositoryTest.java
  src/test/java/postman/bottler/keyword/infra/UserKeywordRepositoryImplTest.java
  src/test/java/postman/bottler/letter/application/service/LetterFacadeServiceTest.java
Labels: refactor

#284 refactor: 키워드 편지 조회시 없을 경우 401 -> 403 반환으로 변경
  src/main/java/postman/bottler/global/response/code/ErrorStatus.java
Labels: refactor

#285 CI-CD: Develop to Main
  src/main/java/postman/bottler/global/response/code/ErrorStatus.java
  src/main/java/postman/bottler/keyword/application/repository/UserKeywordRepository.java
  src/main/java/postman/bottler/keyword/application/service/AsyncRecommendationService.java
  src/main/java/postman/bottler/keyword/application/service/RedisLetterService.java
  src/main/java/postman/bottler/keyword/application/service/UserKeywordService.java
  src/main/java/postman/bottler/keyword/infra/LetterKeywordJdbcRepository.java
  src/main/java/postman/bottler/keyword/infra/UserKeywordJdbcRepository.java
  src/main/java/postman/bottler/keyword/infra/UserKeywordJpaRepository.java
  src/main/java/postman/bottler/keyword/infra/UserKeywordRepositoryImpl.java
  src/main/java/postman/bottler/keyword/presentation/KeywordController.java
  src/main/java/postman/bottler/keyword/presentation/RecommendationController.java
  src/main/java/postman/bottler/keyword/util/RedisLetterKeyUtil.java
  src/main/java/postman/bottler/letter/application/service/LetterFacadeService.java
  src/test/java/postman/bottler/keyword/application/service/AsyncRecommendationServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/RedisLetterServiceTest.java
  src/test/java/postman/bottler/keyword/application/service/UserKeywordServiceTest.java
  src/test/java/postman/bottler/keyword/infra/UserKeywordJpaRepositoryTest.java
  src/test/java/postman/bottler/keyword/infra/UserKeywordRepositoryImplTest.java
  src/test/java/postman/bottler/letter/application/service/LetterFacadeServiceTest.java
Labels: CI-CD

#289 Refactor/#271 exceptions logging
  src/main/java/postman/bottler/global/response/code/ErrorStatus.java
  src/main/java/postman/bottler/keyword/application/service/KeywordService.java
  src/main/java/postman/bottler/keyword/application/service/LetterKeywordService.java
  src/main/java/postman/bottler/keyword/application/service/RecommendService.java
  src/main/java/postman/bottler/keyword/application/service/RedisLetterService.java
  src/main/java/postman/bottler/keyword/application/service/UserKeywordService.java
  src/main/java/postman/bottler/letter/application/dto/request/LetterRequestDTO.java
  src/main/java/postman/bottler/letter/application/service/LetterBoxService.java
  src/main/java/postman/bottler/letter/application/service/LetterDeletionService.java
  src/main/java/postman/bottler/letter/application/service/LetterFacadeService.java
  src/main/java/postman/bottler/letter/application/service/LetterService.java
  src/main/java/postman/bottler/letter/application/service/ReplyLetterService.java
  src/main/java/postman/bottler/letter/domain/BoxType.java
  src/main/java/postman/bottler/letter/domain/Letter.java
  src/main/java/postman/bottler/letter/domain/LetterType.java
  src/main/java/postman/bottler/letter/domain/SortField.java
  src/main/java/postman/bottler/letter/exception/DeveloperLetterException.java
  src/main/java/postman/bottler/letter/exception/DuplicateReplyLetterException.java
  src/main/java/postman/bottler/letter/exception/InvalidInputException.java
  src/main/java/postman/bottler/letter/exception/InvalidLetterRequestException.java
  src/main/java/postman/bottler/letter/exception/InvalidLetterTypeException.java
  src/main/java/postman/bottler/letter/exception/InvalidSortFieldException.java
  src/main/java/postman/bottler/letter/exception/LetterAccessDeniedException.java
  src/main/java/postman/bottler/letter/exception/LetterAlreadySavedException.java
  src/main/java/postman/bottler/letter/exception/LetterAuthorMismatchException.java
  src/main/java/postman/bottler/letter/exception/LetterCustomException.java
  src/main/java/postman/bottler/letter/exception/LetterExceptionHandler.java
  src/main/java/postman/bottler/letter/exception/LetterNotFoundException.java
  src/main/java/postman/bottler/letter/exception/SavedLetterNotFoundException.java
  src/main/java/postman/bottler/letter/exception/TempRecommendationsNotFoundException.java
  src/main/java/postman/bottler/letter/exception/UnauthorizedLetterAccessException.java
  src/main/java/postman/bottler/letter/infra/LetterBoxQueryRepository.java
  src/main/java/postman/bottler/letter/processor/LetterTypeProcessor.java
  src/test/java/postman/bottler/keyword/application/service/LetterKeywordServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterBoxServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterDeletionServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterFacadeServiceTest.java
  src/test/java/postman/bottler/letter/domain/LetterBoxTest.java
  src/test/java/postman/bottler/letter/infra/LetterBoxQueryRepositoryTest.java
  src/test/java/postman/bottler/letter/infra/LetterBoxRepositoryImplTest.java
Labels: refactor

#287 refactor: 추상화 수준 리팩토링
  src/main/java/postman/bottler/complaint/application/service/ComplaintService.java
Labels: refactor

#290 Refactor: 알림 리팩토링
  src/main/java/postman/bottler/complaint/application/service/ComplaintService.java
  src/main/java/postman/bottler/config/RedisConfig.java
  src/main/java/postman/bottler/letter/application/service/ReplyLetterService.java
  src/main/java/postman/bottler/mapletter/application/service/MapLetterService.java
  src/main/java/postman/bottler/notification/application/service/NotificationService.java
  src/main/java/postman/bottler/notification/infra/FirebasePushProvider.java
  src/main/java/postman/bottler/scheduler/RecommendationScheduler.java
  src/main/java/postman/bottler/user/application/service/UserService.java
  src/test/java/postman/bottler/complaint/application/ComplaintServiceTest.java
  src/test/java/postman/bottler/letter/application/service/ReplyLetterServiceTest.java
  src/test/java/postman/bottler/notification/application/NotificationServiceTest.java
  src/test/java/postman/bottler/user/application/UserServiceTest.java
Labels: refactor, fix

#292 Chore : 로그 설정 수정
  .github/workflows/cd.yml
  build.gradle
  docker-compose/docker-compose.yml
Labels: chore

#295 fix: 트랜잭션 문제로 인해 키워드가 일관되지 않게 조회되는 버그 수정
  src/main/java/postman/bottler/keyword/application/repository/LetterKeywordRepository.java
  src/main/java/postman/bottler/keyword/application/service/LetterKeywordService.java
  src/main/java/postman/bottler/keyword/infra/LetterKeywordQueryDslRepository.java
  src/main/java/postman/bottler/keyword/infra/LetterKeywordRepositoryImpl.java
  src/test/java/postman/bottler/keyword/application/service/LetterKeywordServiceTest.java
  src/test/java/postman/bottler/keyword/infra/LetterKeywordRepositoryImplTest.java
Labels: fix

#299 fix: 최근 답장 편지 조회시 원본 편지 아이디가 아니라 답장 편지 아이디를 주도록 수정
  src/main/java/postman/bottler/letter/application/service/ReplyLetterService.java
Labels: fix

#300 Feature/#293 keyword letter delete all
  src/main/java/postman/bottler/keyword/application/service/RedisLetterService.java
  src/main/java/postman/bottler/letter/application/repository/LetterBoxRepository.java
  src/main/java/postman/bottler/letter/application/repository/ReplyLetterRepository.java
  src/main/java/postman/bottler/letter/application/service/LetterBoxService.java
  src/main/java/postman/bottler/letter/application/service/LetterDeletionService.java
  src/main/java/postman/bottler/letter/application/service/LetterService.java
  src/main/java/postman/bottler/letter/application/service/ReplyLetterService.java
  src/main/java/postman/bottler/letter/application/service/deleter/BoxTypeDeleter.java
  src/main/java/postman/bottler/letter/application/service/deleter/LetterDeletionContext.java
  src/main/java/postman/bottler/letter/application/service/deleter/LetterTypeDeleter.java
  src/main/java/postman/bottler/letter/infra/LetterBoxQueryRepository.java
  src/main/java/postman/bottler/letter/infra/LetterBoxRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/ReplyLetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/presentation/LetterBoxController.java
  src/main/java/postman/bottler/letter/processor/LetterTypeProcessor.java
  src/test/java/postman/bottler/keyword/application/service/RedisLetterServiceTest.java
  src/test/java/postman/bottler/letter/application/service/LetterServiceTest.java
Labels: feature

#307 Refactor/#305 logging error response
  src/main/java/postman/bottler/keyword/application/service/KeywordService.java
  src/main/java/postman/bottler/keyword/application/service/LetterKeywordService.java
  src/main/java/postman/bottler/keyword/application/service/RedisLetterService.java
  src/main/java/postman/bottler/keyword/application/service/UserKeywordService.java
  src/main/java/postman/bottler/letter/application/service/LetterBoxService.java
  src/main/java/postman/bottler/letter/application/service/LetterDeletionService.java
  src/main/java/postman/bottler/letter/application/service/LetterService.java
  src/main/java/postman/bottler/letter/application/service/ReplyLetterService.java
  src/main/java/postman/bottler/letter/exception/DuplicateReplyLetterException.java
  src/main/java/postman/bottler/letter/exception/TempRecommendationsNotFoundException.java
Labels: refactor

#306 fix: 메서드 변경 내용 복구
  src/main/java/postman/bottler/complaint/application/service/ComplaintService.java
Labels: fix

#310 Fix/#301 recommend reset
  src/main/java/postman/bottler/keyword/application/dto/RecommendedLetterDTO.java
  src/main/java/postman/bottler/keyword/application/repository/RecommendedLetterRepository.java
  src/main/java/postman/bottler/keyword/application/service/AsyncRecommendationService.java
  src/main/java/postman/bottler/keyword/application/service/RecommendedLetterService.java
  src/main/java/postman/bottler/keyword/application/service/RedisLetterService.java
  src/main/java/postman/bottler/keyword/presentation/RecommendationController.java
  src/main/java/postman/bottler/letter/domain/RecommendedLetter.java
  src/main/java/postman/bottler/letter/infra/RecommendedLetterJpaRepository.java
  src/main/java/postman/bottler/letter/infra/RecommendedLetterRepositoryImpl.java
  src/main/java/postman/bottler/letter/infra/entity/RecommendedLetterEntity.java
  src/main/java/postman/bottler/scheduler/RecommendationScheduler.java
  src/test/java/postman/bottler/keyword/application/service/RedisLetterServiceTest.java
  src/test/java/postman/bottler/scheduler/RecommendationSchedulerTest.java
Labels: fix
